name: release-please

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
    outputs:
       release_created: ${{ steps.release.outputs.release_created }}

  docs:
    # needs: generate-changelog
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    uses: ./.github/workflows/publish-docs.yaml
    with:
      message: 'Warning: This is the development version.'

  #deploy-prod:
  #  needs: release-please
  #  uses: ./.github/workflows/release-production.yaml
  #  if: ${{ needs.release-please.outputs.release_created }}
  #  secrets:
  #    APP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.APP_SERVICE_ACCOUNT_TOKEN }}